apiVersion: apps/v1
kind: Deployment
metadata:
  name: caravana-land
  namespace: caravana
  labels:
    app: caravana-land
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caravana-land
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: caravana-land
    spec:
      containers:
      - name: caravana-land
        image: caravanahub/caravana-land:17
        ports:
        - containerPort: 4000
        env:
        - name: HOST
          value: caravana.dev 
        - name: PORT
          value: "4000"
        - name: SECRET_KEY_BASE
          value: Zks/p88uM3Y/d8NTUIeJ93UiG+Atnb94EDVY7w5G05YL/Bk/Ij2U6Onx4Pyl5bjm
        - name: TRELLO_KEY
          value: b18a9b19ee35f035ad85154792b4402b
        - name: TRELLO_TOKEN
          value: 74aa519384c8ac3326712c03ebd65064178f0a66d282aacb510fabd150c381fc
        - name: TRELLO_LIST_ID
          value: 60799d81fcaa6d32260c43e3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: caravana-land
  namespace: caravana
  labels:
    app: caravana-land
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
  selector:
    app: caravana-land
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caravana-land-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - caravana.dev
      secretName: caravana-land-tls
  rules:
    - host: caravana.dev
      http:
        paths:
        - backend:
            service:
              name: caravana-land
              port:
                number: 80
          pathType: ImplementationSpecific


