apiVersion: v1
kind: Service
metadata:
  name: caravana-land
  labels:
    app: ceibo-land
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 4000
  selector:
    app: ceibo-land
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caravana-land-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - caravana.dev
      secretName: caravana-land-tls
  rules:
    - host: caravana.dev
      http:
        paths:
        - backend:
            service:
              name: caravana-land
              port:
                number: 80
          pathType: ImplementationSpecific


